# ********RoostGPT********
"""
Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4

ROOST_TEST_HASH=ip_address_helper_e02f7654d2

1. Scenario: Valid Hostname
   Description: Validate that the function returns the correct IP address when the hostname is valid. The expected result is the IP address associated with the hostname.

2. Scenario: Invalid Hostname
   Description: Validate that the function returns an error message when the hostname is invalid or does not exist. The expected result is "IP Error!".

3. Scenario: Empty Hostname
   Description: Validate that the function returns an error message when the hostname is empty. The expected result is "IP Error!".

4. Scenario: Localhost as Hostname
   Description: Validate that the function returns the correct IP address when the hostname is localhost. The expected result is "127.0.0.1".

5. Scenario: Network Disconnected
   Description: Validate that the function returns an error message when the network is disconnected. The expected result is "IP Error!".

6. Scenario: Network Reconnected
   Description: Validate that the function returns the correct IP address when the network is reconnected after being disconnected. The expected result is the IP address associated with the hostname.

7. Scenario: Hostname Changed
   Description: Validate that the function returns the correct IP address when the hostname is changed. The expected result is the new IP address associated with the new hostname.

8. Scenario: IP Address Changed
   Description: Validate that the function returns the updated IP address when the IP address associated with the hostname is changed. The expected result is the new IP address.

9. Scenario: Hostname Contains Special Characters
   Description: Validate that the function returns an error message when the hostname contains special characters. The expected result is "IP Error!". 

10. Scenario: Hostname Contains Whitespaces
    Description: Validate that the function returns an error message when the hostname contains whitespaces. The expected result is "IP Error!".

Note: The actual results might vary based on the network and system configurations.
"""

# ********RoostGPT********
def calculator(operation, num1, num2):
    if operation == 'add':
        return num1 + num2
    elif operation == 'subtract':
        return num1 - num2
    elif operation == 'multiply':
        return num1 * num2
    elif operation == 'divide':
        return num1 / num2
    else:
        return 'Invalid operation'
