# ********RoostGPT********
"""
Test generated by RoostGPT for test MiniProjects using AI Type Open AI and AI Model gpt-4

ROOST_TEST_HASH=send_local_769a5dcbb7

1. Scenario: Path is '/favicon.ico' and 'favicon.ico' file exists in the directory.
   Expected Result: The superclass's 'do_GET' method should be invoked.

2. Scenario: Path is '/favicon.ico' and 'favicon.ico' file does not exist in the directory.
   Expected Result: The 'favicon.ico' file should be base64 decoded and a simple response with this decoded icon and 'image/x-icon' content type should be sent.

3. Scenario: Path is '/ZoomRemoteDir' and the directory listing of the current file's directory is successful. 
   Expected Result: The directory listing should be copied to the output stream and the file object should be closed.

4. Scenario: Path is '/ZoomRemoteDir' and the directory listing of the current file's directory is not successful. 
   Expected Result: The file object should be closed without any further operations.

5. Scenario: Path is neither '/favicon.ico' nor '/ZoomRemoteDir' and 'index.html' file exists in the directory.
   Expected Result: The superclass's 'do_GET' method should be invoked.

6. Scenario: Path is neither '/favicon.ico' nor '/ZoomRemoteDir' and 'index.html' file does not exist in the directory.
   Expected Result: The 'index.html' file should be encoded to 'utf-8' and a simple response with this encoded html and 'text/html' content type should be sent.

7. Scenario: Invalid path is given which is not '/favicon.ico', '/ZoomRemoteDir' or any existing file.
   Expected Result: The function should handle this gracefully without throwing any error. It should return a default response or an error message.

8. Scenario: Permission issues while accessing the files or directories.
   Expected Result: The function should handle this gracefully, possibly by logging an error message and returning a suitable response.

9. Scenario: Network issues while sending the response.
   Expected Result: The function should handle this gracefully, possibly by logging an error message and returning a suitable response.

10. Scenario: The file or directory to be accessed is currently being used by another process.
    Expected Result: The function should handle this gracefully, possibly by logging an error message and returning a suitable response.
"""

# ********RoostGPT********
def calculator(operation, num1, num2):
    if operation == 'add':
        return num1 + num2
    elif operation == 'subtract':
        return num1 - num2
    elif operation == 'multiply':
        return num1 * num2
    elif operation == 'divide':
        return num1 / num2
    else:
        return 'Invalid operation'
